name: Run Unit Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the code from GitHub

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'v22.11.0'  # Specify the Node.js version

      - name: Install dependencies
        run: npm install  # Install dependencies using npm

      - name: Run tests
        run: npm test  # Run the tests using the test script in package.json

      
