name: Run Unit Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout your repository code

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.11.0'  # Specify the correct Node.js version

      - name: Install dependencies
        run: npm install  # Install dependencies from package.json

      - name: Run tests
        run: npm test  # Run the tests using the 'test' script from package.json

      
